Controllers/ContactController.cs
using ContactControl.Filters;
using ContactControl.Helpper;
using ContactControl.Models;
using ContactControl.Repos;
using Microsoft.AspNetCore.Mvc;

namespace ContactControl.Controllers
{
    [LoggedUserPage]
    public class ContactController : Controller
    {
        private readonly IContactRepos _contactRepos;
        private readonly ISessionHelper _session;
        public ContactController(IContactRepos contactRepos, ISessionHelper session)
        {
            _contactRepos = contactRepos;
            _session = session;
        }
        [HttpGet]
        public IActionResult Index()
        {
            UserModel user = _session.GetUserSession();
            List<ContactModel> contacts = _contactRepos.GetAllContacts(user.Id);
            return View(contacts);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ContactModel contact = _contactRepos.GetContactById(id);
            return View(contact);
        }
        [HttpGet]
        public IActionResult DeleteConfirm(int id)
        {
            ContactModel contact = _contactRepos.GetContactById(id);
            return View(contact);
        }
        public IActionResult Delete(int id)
        {
            try
            {
                _contactRepos.DeleteContact(id);
                TempData["success"] = "Contact deleted successfully";
                return RedirectToAction("Index");
            }catch(Exception ex)
            {
                TempData["error"] = $"something went wrong{ex.Message}";
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public IActionResult Create(ContactModel contactModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UserModel user = _session.GetUserSession();
                    contactModel.UserId = user.Id;
                    _contactRepos.AddContact(contactModel);
                    TempData["success"] = "Contact created successfully";
                    return RedirectToAction("Index");
                }
                return View(contactModel);
            }catch(Exception ex)
            {
                TempData["error"] = $"something went wrong{ex.Message}";
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public IActionResult Edit(ContactModel contactModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UserModel user = _session.GetUserSession();
                    contactModel.UserId = user.Id;
                    _contactRepos.UpdateContact(contactModel);
                    TempData["success"] = "Contact updated successfully";
                    return RedirectToAction("Index");
                }
                return View(contactModel);
            }catch(Exception ex)
            {
                TempData["error"] = $"something went wrong{ex.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Contact/Create.cshtml
@model ContactModel
@{
    ViewData["Title"] = "Create";
}
<div class="text-center">
    <h1 class="display-4">Create Contact</h1>
</div>

<form asp-controller="Contact" asp-action="Create" method="post">
    <div class="mb-3">
        <label for="name">Name</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Enter name">
        @Html.ValidationMessageFor(x => x.Name)
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email address</label>
        <input type="email" asp-for="Email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
        @Html.ValidationMessageFor(x => x.Email)
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
        <label for="phone">Phone</label>
        <input type="text" asp-for="Phone" class="form-control" placeholder="Enter phone">
        @Html.ValidationMessageFor(x => x.Phone)
    </div>
    <div class="d-flex justify-content-end gap-2">
        <button type="submit" class="btn btn-primary">Submit</button>
        <a class="btn btn-secondary" asp-controller="Contact" asp-action="Index" role="button">Back</a>
    </div>
</form>

Views/Contact/DeleteConfirm.cshtml
@model ContactModel
@{
    ViewData["Title"] = "Delete";
}
<div class="text-center">
    <h3>Are you sure you want to delete this contact (@Model.Name)?</h3>
</div>
<br />
<div class="d-flex justify-content-center gap-2">
    <a class="btn btn-primary" role="button" asp-controller="Contact" asp-action="Index">Cancel</a>
    <a class="btn btn-primary" role="button" asp-controller="Contact" asp-route-id="@Model.Id" asp-action="Delete">Delete</a>
</div>

Views/Contact/Edit.cshtml
@model ContactModel
@{
    ViewData["Title"] = "Edit";
}
<div class="text-center">
    <h1 class="display-4">Edit Contact</h1>
</div>

<form asp-controller="Contact" asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label for="name">Name</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Enter name">
        @Html.ValidationMessageFor(x => x.Name)
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email address</label>
        <input type="email" asp-for="Email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
        @Html.ValidationMessageFor(x => x.Email)
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
        <label for="phone">Phone</label>
        <input type="text" asp-for="Phone" class="form-control" placeholder="Enter phone">
        @Html.ValidationMessageFor(x => x.Phone)
    </div>
    <div class="d-flex justify-content-end gap-2">
        <button type="submit" class="btn btn-primary">Save</button>
        <a class="btn btn-secondary" asp-controller="Contact" asp-action="Index" role="button">Back</a>
    </div>
</form>

Views/Contact/Index.cshtml
@model List<ContactModel>
@{
    ViewData["Title"] = "Contact List";
}
<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a role="button" class="btn btn-primary" asp-controler="Contact" asp-action="Create">Create</a>
    </div>
    <br />
    @if(TempData["success"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["success"]
        </div>
    }
    @if(TempData["error"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["error"]
        </div>
    }
    <br />
    <h1 class="display-4">Contact List</h1>

    <table class="table" id="table-contacts">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Contact</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if(Model != null && Model.Any())
            {
                @foreach(ContactModel contact in Model)
                {
<tr>
                        <th scope="row">@contact.Id</th>
                        <td>@contact.Name</td>
                        <td>@contact.Email</td>
                        <td>@contact.Phone</td>
                        <td>
                            <a role="button" class="btn btn-primary" asp-controller="Contact" asp-action="Edit" asp-route-id="@contact.Id">Edit</a>
                            <a role="button" class="btn btn-danger" asp-controller="Contact" asp-action="DeleteConfirm" asp-route-id="@contact.Id">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>